// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPath():Promise<string>;

export function GetFontScale():Promise<number>;

export function GetLaunchArgs():Promise<Array<string>>;

export function GetPalette():Promise<string>;

export function GetTheme():Promise<string>;

export function IsDirty():Promise<boolean>;

export function ListThemes():Promise<Array<string>>;

export function LoadFile(arg1:string):Promise<string>;

export function OpenFile():Promise<string>;

export function OpenInPreview():Promise<void>;

export function SaveFile(arg1:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetFontScale(arg1:number):Promise<void>;

export function SetPalette(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
