// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentPath() {
  return window['go']['main']['App']['GetCurrentPath']();
}

export function GetFontScale() {
  return window['go']['main']['App']['GetFontScale']();
}

export function GetLaunchArgs() {
  return window['go']['main']['App']['GetLaunchArgs']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenInPreview() {
  return window['go']['main']['App']['OpenInPreview']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetFontScale(arg1) {
  return window['go']['main']['App']['SetFontScale'](arg1);
}

export function SetPalette(arg1) {
  return window['go']['main']['App']['SetPalette'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
