// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLaunchArgs():Promise<Array<string>>;

export function GetTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListThemes():Promise<Array<string>>;

export function OpenAndRender(arg1:string):Promise<main.RenderResult>;

export function RenderFile(arg1:string,arg2:string):Promise<string>;

export function RenderMarkdown(arg1:string,arg2:string):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
