// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLaunchArgs() {
  return window['go']['main']['App']['GetLaunchArgs']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function OpenAndRender(arg1) {
  return window['go']['main']['App']['OpenAndRender'](arg1);
}

export function RenderFile(arg1, arg2) {
  return window['go']['main']['App']['RenderFile'](arg1, arg2);
}

export function RenderMarkdown(arg1, arg2) {
  return window['go']['main']['App']['RenderMarkdown'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
