// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSearch() {
  return window['go']['main']['App']['ClearSearch']();
}

export function GetAutoReload() {
  return window['go']['main']['App']['GetAutoReload']();
}

export function GetFontScale() {
  return window['go']['main']['App']['GetFontScale']();
}

export function GetLaunchArgs() {
  return window['go']['main']['App']['GetLaunchArgs']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetSearchCaseSensitive() {
  return window['go']['main']['App']['GetSearchCaseSensitive']();
}

export function GetSearchHighlightColor() {
  return window['go']['main']['App']['GetSearchHighlightColor']();
}

export function GetSearchState() {
  return window['go']['main']['App']['GetSearchState']();
}

export function GetTOCPinned() {
  return window['go']['main']['App']['GetTOCPinned']();
}

export function GetTOCVisible() {
  return window['go']['main']['App']['GetTOCVisible']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function NavigateSearch(arg1) {
  return window['go']['main']['App']['NavigateSearch'](arg1);
}

export function OpenAndRender(arg1, arg2) {
  return window['go']['main']['App']['OpenAndRender'](arg1, arg2);
}

export function OpenInEditor() {
  return window['go']['main']['App']['OpenInEditor']();
}

export function RenderFile(arg1, arg2) {
  return window['go']['main']['App']['RenderFile'](arg1, arg2);
}

export function RenderFileWithPalette(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderFileWithPalette'](arg1, arg2, arg3);
}

export function RenderFileWithPaletteAndTOC(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderFileWithPaletteAndTOC'](arg1, arg2, arg3);
}

export function RenderMarkdown(arg1, arg2) {
  return window['go']['main']['App']['RenderMarkdown'](arg1, arg2);
}

export function RenderMarkdownWithPalette(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderMarkdownWithPalette'](arg1, arg2, arg3);
}

export function SearchDocument(arg1, arg2) {
  return window['go']['main']['App']['SearchDocument'](arg1, arg2);
}

export function SetAutoReload(arg1) {
  return window['go']['main']['App']['SetAutoReload'](arg1);
}

export function SetCurrentDocument(arg1) {
  return window['go']['main']['App']['SetCurrentDocument'](arg1);
}

export function SetFontScale(arg1) {
  return window['go']['main']['App']['SetFontScale'](arg1);
}

export function SetPalette(arg1) {
  return window['go']['main']['App']['SetPalette'](arg1);
}

export function SetSearchCaseSensitive(arg1) {
  return window['go']['main']['App']['SetSearchCaseSensitive'](arg1);
}

export function SetSearchHighlightColor(arg1) {
  return window['go']['main']['App']['SetSearchHighlightColor'](arg1);
}

export function SetTOCPinned(arg1) {
  return window['go']['main']['App']['SetTOCPinned'](arg1);
}

export function SetTOCVisible(arg1) {
  return window['go']['main']['App']['SetTOCVisible'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartWatchingFile(arg1) {
  return window['go']['main']['App']['StartWatchingFile'](arg1);
}

export function StopWatchingFile() {
  return window['go']['main']['App']['StopWatchingFile']();
}
