// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSearch():Promise<void>;

export function GetAutoReload():Promise<boolean>;

export function GetFontScale():Promise<number>;

export function GetLaunchArgs():Promise<Array<string>>;

export function GetPalette():Promise<string>;

export function GetSearchCaseSensitive():Promise<boolean>;

export function GetSearchHighlightColor():Promise<string>;

export function GetSearchState():Promise<main.SearchResult>;

export function GetTOCPinned():Promise<boolean>;

export function GetTOCVisible():Promise<boolean>;

export function GetTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListThemes():Promise<Array<string>>;

export function NavigateSearch(arg1:string):Promise<main.SearchResult>;

export function OpenAndRender(arg1:string,arg2:string):Promise<main.RenderResult>;

export function OpenInEditor():Promise<void>;

export function RenderFile(arg1:string,arg2:string):Promise<string>;

export function RenderFileWithPalette(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RenderFileWithPaletteAndTOC(arg1:string,arg2:string,arg3:string):Promise<main.RenderResult>;

export function RenderMarkdown(arg1:string,arg2:string):Promise<string>;

export function RenderMarkdownWithPalette(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchDocument(arg1:string,arg2:boolean):Promise<main.SearchResult>;

export function SetAutoReload(arg1:boolean):Promise<void>;

export function SetCurrentDocument(arg1:string):Promise<void>;

export function SetFontScale(arg1:number):Promise<void>;

export function SetPalette(arg1:string):Promise<void>;

export function SetSearchCaseSensitive(arg1:boolean):Promise<void>;

export function SetSearchHighlightColor(arg1:string):Promise<void>;

export function SetTOCPinned(arg1:boolean):Promise<void>;

export function SetTOCVisible(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartWatchingFile(arg1:string):Promise<void>;

export function StopWatchingFile():Promise<void>;
